### ISSUE TITLE
Attunement

### ISSUE THREAD

**Issue by sooskca** [sooskca/strangematter#3]
Implements The Attunement System

- [ ] #3 The item reacts on receiving attunement points
- [ ] #4 The item changes color to represent it's attunement level
- [ ] #3 The item imbues weapons, allowing for its fueling
- [ ] #5 The item grants abilities based on its attunement
- [ ] #6 Foes slain by imbued weapons have a special death animation
